# Generated by Django 5.2 on 2025-05-13 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('asignation_date', models.DateTimeField(verbose_name='Asignation Date')),
                ('limit_date', models.DateTimeField(verbose_name='Limit Date')),
                ('detail', models.TextField()),
                ('finalization_date', models.DateTimeField(blank=True, null=True, verbose_name='Finalization Date')),
                ('priority', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('observation', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.proyect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
