# Generated by Django 5.2 on 2025-04-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('asignation_date', models.DateField(auto_now_add=True, verbose_name='Asignation Date')),
                ('limit_date', models.DateField(auto_now_add=True, verbose_name='Limit Date')),
                ('detail', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('observation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
