# Generated by Django 5.2 on 2025-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
