# Generated by Django 5.2 on 2025-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='asignation_date',
            field=models.DateField(verbose_name='Asignation Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='limit_date',
            field=models.DateField(verbose_name='Limit Date'),
        ),
    ]
