# Generated by Django 5.2 on 2025-04-11 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_asignation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
