# Generated by Django 5.2 on 2025-04-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='days',
        ),
        migrations.AddField(
            model_name='activity',
            name='finalization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finalization Date'),
        ),
    ]
