# Generated by Django 5.2 on 2025-04-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activity_days_activity_finalization_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
