# Generated by Django 5.2 on 2025-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='asignation_date',
            field=models.DateTimeField(verbose_name='Asignation Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='finalization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalization Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='limit_date',
            field=models.DateTimeField(verbose_name='Limit Date'),
        ),
    ]
