# Generated by Django 5.2 on 2025-04-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('imported', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('type_change', models.FloatField()),
                ('bill_text', models.CharField(max_length=200)),
                ('date_bill', models.DateField(verbose_name='Bill Date')),
                ('model', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('date_manufacture', models.DateField(verbose_name='Manufacture Date')),
                ('minsa_code', models.CharField(max_length=100)),
                ('minsa_description', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('entry_point', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_point', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(verbose_name='Date')),
                ('entry_guide', models.CharField(max_length=200)),
                ('proyect', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=100)),
                ('coin_bill', models.CharField(max_length=100)),
            ],
        ),
    ]
