# Generated by Django 5.2 on 2025-04-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_enter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_exit',
        ),
    ]
