# Generated by Django 5.2 on 2025-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exit_guide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
