# Generated by Django 5.2 on 2025-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_exit_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exit Date'),
        ),
    ]
