# Generated by Django 5.2 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bill_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_bill',
            field=models.DateField(blank=True, null=True, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_manufacture',
            field=models.DateField(blank=True, null=True, verbose_name='Manufacture Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='entry_guide',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
