# Generated by Django 5.2 on 2025-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_quantity_total_alter_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_total_exit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
