# Generated by Django 5.2 on 2025-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_alter_serie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='quantity_enter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='quantity_exit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
