# Generated by Django 5.2 on 2025-04-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0003_serie_quantity_enter_serie_quantity_exit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='is_enter',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='is_exit',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='quantity_enter',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='quantity_exit',
        ),
    ]
