# Generated by Django 5.2 on 2025-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
