# Generated by Django 5.2 on 2025-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'coordination'), (3, 'biomedical'), (2, 'admin'), (4, 'accountant')], default=3, null=True),
        ),
    ]
