# Generated by Django 5.2 on 2025-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=100)),
                ('activity_detail', models.TextField()),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Arrival Date')),
                ('final_date', models.DateField(auto_now_add=True, verbose_name='Final Date')),
                ('initial_date', models.DateField(auto_now_add=True, verbose_name='Initial Date')),
                ('priority', models.CharField(max_length=100)),
                ('job_order', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('observation', models.TextField()),
            ],
        ),
    ]
