# Generated by Django 5.2 on 2025-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='arrival_date',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='final_date',
            field=models.DateField(verbose_name='Final Date'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='initial_date',
            field=models.DateField(verbose_name='Initial Date'),
        ),
    ]
