# Generated by Django 5.2 on 2025-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_alter_coordination_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
