# Generated by Django 5.2 on 2025-04-14 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_alter_coordination_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordination',
            name='register_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Register Date'),
            preserve_default=False,
        ),
    ]
