# Generated by Django 5.2 on 2025-04-14 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0004_coordination_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordination',
            name='days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
