# Generated by Django 5.2 on 2025-04-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0005_coordination_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordination',
            name='days',
        ),
    ]
