# Generated by Django 5.2 on 2025-04-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0007_alter_coordination_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final Date'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='initial_date',
            field=models.DateTimeField(verbose_name='Initial Date'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Register Date'),
        ),
    ]
