# Generated by Django 5.2 on 2025-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_alter_entry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
